SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_animais_usuarios_usuario_id". The conflict occurred in database "MiAuDota", table "dbo.usuarios", column 'Id'. The statement has been terminated.